language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  ## Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
  ## Use either `docker-compose` or individual `docker build` commands
  ## Build
  - docker --version # print the version for logging

  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy

  ## Tagging
  - docker tag udagram-api-feed callmefox/udagram-api-feed
  - docker tag udagram-api-user callmefox/udagram-api-user
  - docker tag udagram-frontend callmefox/udagram-frontend
  - docker tag reverseproxy callmefox/reverseproxy

after_success:
  - echo Tuan1234@ | docker login -u callmefox --password-stdin
  ## Push
  - docker push callmefox/udagram-api-feed
  - docker push callmefox/udagram-api-user
  - docker push callmefox/udagram-frontend
  - docker push callmefox/reverseproxy

## Do similar for other three images