language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  ## Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
  ## Use either `docker-compose` or individual `docker build` commands
  ## Build
  - docker --version # print the version for logging

  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy

  ## Tagging
  - docker tag udagram-api-feed fox-88201/udagram-api-feed
  - docker tag udagram-api-user fox-88201/udagram-api-user
  - docker tag udagram-frontend fox-88201/udagram-frontend
  - docker tag reverseproxy fox-88201/reverseproxy

after_success:
  - echo Tuan1234@ | docker login -u callmefox --password-stdin
  ## Push
  - docker push fox-88201/udagram-api-feed
  - docker push fox-88201/udagram-api-user
  - docker push fox-88201/udagram-frontend
  - docker push fox-88201/reverseproxy

## Do similar for other three images